# Generated by Django 3.1.7 on 2021-03-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-date_created']},
        ),
        migrations.AddField(
            model_name='project',
            name='featured_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
