# Generated by Django 3.1.7 on 2021-03-10 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0004_auto_20210309_1723'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectImages',
            new_name='Image',
        ),
    ]
