# Generated by Django 3.1.7 on 2021-03-10 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0005_auto_20210310_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='project_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio_app.project'),
        ),
    ]
